# Generated by Django 3.0.5 on 2020-04-26 20:32

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200427_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='document',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
